name: Lands
main: me.angeschossen.lands.Lands
version: ${project.version}
author: 'Angeschossen'
description: 'Feature rich GUI, Taxes, Customize your own, Titles, New factions - Let players manage their land!'
website: 'https://www.spigotmc.org/resources/53313'
api-version: '1.13'
load: POSTWORLD

softdepend: [Vault, dynmap, HolographicDisplays, WorldGuard, WorldEdit, PlaceholderAPI]

commands:
  lands:
    aliases: [land, l]
    description: 'Manage your land.'
  wars:
    aliases: [war, w]
    description: 'Lands war command.'
  nations:
    aliases: [nation, n]
    description: 'Lands nation command.'

permissions:
  lands.*:
    description: Access to all Lands actions
    default: op
    children:
      lands.chunks.NUMBER:
        description: Set max chunk claims
        default: op
      lands.chunks.support.NUMBER:
        description: Support lands, in which you're member of, with additional claims
        default: op
      lands.lands.NUMBER:
        description: Set max lands can be member of (own lands + lands where member)
        default: op
      lands.ownlands.NUMBER:
        description: Set max own lands (own lands)
        default: op
      lands.members.NUMBER:
        description: Set max members in a land
        default: op
      lands.selection.NUMBER:
        description: Set max chunks in selection (/Lands selection)
        default: op
      lands.chunks.max.NUMBER:
        description: ONLY NEEDED IF OPTION PLAYTIME REWARDS IS ENABLED Set max chunks a player can get through playtime rewards
        default: op
      lands.lands.max.NUMBER:
        description: ONLY NEEDED IF OPTION PLAYTIME REWARDS IS ENABLED Set max lands a player can get through playtime rewards
        default: op
      lands.members.max.NUMBER:
        description: ONLY NEEDED IF OPTION PLAYTIME REWARDS IS ENABLED Set max members the players land can have through playtime rewards
        default: op
      lands.ownlands.max.NUMBER:
        description: ONLY NEEDED IF OPTION PLAYTIME REWARDS IS ENABLED Set max lands a player can own through playtime rewards
        default: op
      lands.free.*:
        description: Player doesn't need to pay claim and land creation costs
        default: op
        children:
          lands.free.chunks.NUMBER:
            description: Set free chunk claims
            default: op
          lands.free.lands.NUMBER:
            description: Set free land creations
            default: op
      lands.command.*:
        description: Access to all player commands
        children:
          lands.command.accept:
            description: /Lands accept
            default: op
          lands.command.chat:
            description: /Lands chat
            default: op
          lands.command.claim:
            description: /Lands claim
            default: op
          lands.command.create:
            description: /Lands create
            default: op
          lands.command.delete:
            description: /Lands delete
            default: op
          lands.command.deny:
            description: /Lands deny
            default: op
          lands.command.deposit:
            description: /Lands deposit
            default: op
          lands.command.edit:
            description: /Lands edit
            default: op
          lands.command.help:
            description: /Lands help
            default: op
          lands.command.info:
            description: /Lands info
            default: op
          lands.command.invites:
            description: /Lands invites
            default: op
          lands.command.leave:
            description: /Lands leave
            default: op
          lands.command.menu:
            description: /Lands menu
            default: op
          lands.command.rename:
            description: /Lands rename
            default: op
          lands.command.selection:
            description: /Lands selection
            default: op
          lands.command.setrole:
            description: /Lands setrole
            default: op
          lands.command.setspawn:
            description: /Lands setspawn
            default: op
          lands.command.spawn:
            description: /Lands spawn
            default: op
          lands.command.teleport:
            description: /Lands teleport
            default: op
          lands.command.top:
            description: /Lands top
            default: op
          lands.command.trust:
            description: /Lands trust
            default: op
          lands.command.unclaim:
            description: /Lands unclaim
            default: op
          lands.command.untrust:
            description: /Lands untrust
            default: op
          lands.command.view:
            description: /Lands view
            default: op
          lands.command.view.toggle:
            description: /Lands view toggle
            default: op
          lands.command.withdraw:
            description: /Lands withdraw
            default: op
          lands.command.wild:
            description: /Lands wild
            default: op
          lands.command.list:
            description: /Lands list
            default: op
          lands.command.ban:
            description: /Lands banF
            default: op
          lands.command.unban:
            description: /Lands unban
            default: op
      lands.bypass.*:
        description: Bypass all protections and other restrictions
        children:
          lands.bypass.block_break:
            description: Bypass block break protection
            default: op
          lands.bypass.block_place:
            description: Bypass block place protection
            default: op
          lands.bypass.block_ignite:
            description: Bypass block ignite protection
            default: op
          lands.bypass.interact_general:
            description: Bypass interaction protection
            default: op
          lands.bypass.interact_mechanism:
            description: Bypass interaction protection
            default: op
          lands.bypass.interact_door:
            description: Bypass interaction protection
            default: op
          lands.bypass.interact_container:
            description: Bypass interaction protection
            default: op
          lands.bypass.attack_animal:
            description: Bypass animal attack protection
            default: op
          lands.bypass.attack_player:
            description: Bypass player attack protection
            default: op
          lands.bypass.member.untrust:
            description: Untrust players or remove invites in other lands
            default: op
          lands.bypass.fly:
            description: Bypass fly flag
            default: op
          lands.bypass.worldedit:
            description: Bypass WorldEdit restrictions in other players lands
            default: op
          lands.bypass.edit.*:
            description: Select lands you're not member of
            default: op
            children:
              lands.bypass.edit.settings:
                description: Edit settings of other lands
                default: op
          lands.bypass.selection:
            description: Bypass error message of other plugin cancelling selection
            default: op
          lands.bypass.teleport-delay:
            description: Bypass teleportation delays / warmups
            default: op
          lands.bypass.wilderness.*:
            description: Bypass all wilderness protections (for worlds in disallow-wilderness_list)
            default: op
            children:
              lands.bypass.wilderness.block_break:
                description: Bypass block break protection for disallow-wilderness_list in config
                default: op
              lands.bypass.wilderness.block_place:
                description: Bypass block place protection for disallow-wilderness_list in config
                default: op
              lands.bypass.wilderness.block_ignite:
                description: Bypass block ignite protection for disallow-wilderness_list in config
                default: op
              lands.bypass.wilderness.interact_general:
                description: Bypass interaction protection for disallow-wilderness_list in config
                default: op
              lands.bypass.wilderness.interact_mechanism:
                description: Bypass interaction protection for disallow-wilderness_list in config
                default: op
              lands.bypass.wilderness.interact_door:
                description: Bypass interaction protection for disallow-wilderness_list in config
                default: op
              lands.bypass.wilderness.interact_container:
                description: Bypass interaction protection for disallow-wilderness_list in config
                default: op
              lands.bypass.wilderness.attack_animal:
                description: Bypass animal attack protection for disallow-wilderness_list in config
                default: op
              lands.bypass.wilderness.attack_player:
                description: Bypass player attack protection for disallow-wilderness_list in config
                default: op
              lands.bypass.wilderness.worldedit:
                description: Bypass WorldEdit restrictions in wilderness.
                default: op
              lands.bypass.wilderness.teleport:
                description: Teleport to wilderness (unclaimed chunks) through /Lands teleport.
                default: op
              lands.bypass.wilderness.fly:
                description: Fly in wilderness
                default: op
          lands.bypass.cooldown.*:
            description: Bypass cooldowns
            default: op
            children:
              lands.bypass.cooldown.wild:
                description: Bypass /Lands wild cooldown
                default: op
              lands.bypass.cooldown.rename:
                description: Bypass /Lands rename cooldown
                default: op
              lands.bypass.cooldown.teleport:
                description: Bypass chunk teleport cooldown
                default: op
              lands.bypass.cooldown.spawn:
                description: Bypass /Lands spawn cooldown
                default: op
          lands.bypass.spawn.private:
            description: Teleport to private land spawns
            default: op
          lands.bypass.option.*:
            description: Bypass special config options.
            default: op
            children:
              lands.bypass.option.force-near:
                description: Bypass force-near option from config.
                default: op
              lands.bypass.option.chunk-distance:
                description: Bypass chunk-distance option from config.
                default: op
      lands.gui.*:
        description: Access to all GUI actions
        default: op
        children:
          lands.gui.chunk.*:
            description: Access to all chunk GUI actions
            default: op
            children:
              lands.gui.chunk.teleport:
                description: Allow teleporting to claimed chunks
                default: op

      lands.setting.*:
        description: Access to land settings
        default: op
        children:
          lands.setting.entity_griefing:
            description: Allow to toggle entity griefing
            default: op
          lands.setting.piston_griefing:
            description: Allow to toggle piston griefing
            default: op
          lands.setting.monster_spawn:
            description: Allow to toggle monster spawn
            default: op
          lands.setting.animal_spawn:
            description: Allow to toggle animal spawn
            default: op
          lands.setting.waterflow_allow:
            description: Allow to toggle waterflow
            default: op
          lands.setting.tnt_griefing:
            description: Toggle Flag - Allow tnt griefing inside a land / area.

      lands.role.*:
        description: Access to all role settings
        default: op
        children:
          lands.role.setting.*:
            description: Access to all role settings (toggle)
            default: op
            children:
              lands.role.setting.block_break:
                description: Allow to toggle block break
                default: op
              lands.role.setting.block_place:
                description: Allow to toggle block place
                default: op
              lands.role.setting.attack_player:
                description: Allow to toggle attack player
                default: op
              lands.role.setting.attack_animal:
                description: Allow to toggle attack animal
                default: op
              lands.role.setting.block_ignite:
                description: Allow to toggle block ignite
                default: op
              lands.role.setting.interact_general:
                description: Allow to toggle general interaction
                default: op
              lands.role.setting.interact_door:
                description: Allow to toggle open doors
                default: op
              lands.role.setting.interact_container:
                description: Allow to toggle open container
                default: op
              lands.role.setting.interact_mechanism:
                description: Allow to toggle interact mechanism (redstone)
                default: op
              lands.role.setting.interact_villager:
                description: Toggle Flag - Allow a role to interact with villager.
                default: op
              lands.role.setting.fly:
                description: Toggle Flag - Allow a role to fly inside the land / area.
                default: op
              lands.role.setting.land_enter:
                description: Toggle Flag - Allow a role to enter the land / area.
              lands.role.setting.player_trust:
                description: Allow to toggle trust player
                default: op
              lands.role.setting.player_untrust:
                description: Allow to toggle player untrust
                default: op
              lands.role.setting.player_setrole:
                description: Allow to toggle player setrole
                default: op
              lands.role.setting.land_claim:
                description: Allow to toggle claim chunks for the land
                default: op
              lands.role.setting.land_claim_border:
                description: Allow to toggle claim chunks at the border of the land
                default: op
              lands.role.setting.spawn_set:
                description: Allow to toggle spawn set
                default: op
              lands.role.setting.spawn_teleport:
                description: Allow to toggle spawn teleport
                default: op
              lands.role.setting.land_rename:
                description: Allow to toggle rename land setting
                default: op
              lands.role.setting.setting_edit:
                description: Allow to toggle allow this role to change settings of a role with lower priority
                default: op
              lands.role.setting.balance_withdraw:
                description: Toggle Flag - Allow a role to withdraw money from the land bank
                default: op
              lands.role.setting.area_assign:
                description: Toggle Flag - Allow a role to assign a selection to a area.
                default: op
              lands.role.setting.setting_edit_advanced:
                description: Toggle Flag - Allow a role to edit advanced settings.
                default: op
              lands.role.setting.setting_edit_land:
                description: Toggle Flag - Allow a role to edit land settings.
                default: op
              lands.role.setting.setting_edit_role:
                description: Toggle Flag - Allow a role to edit role settings of roles with a lower priority.
                default: op
              lands.role.setting.setting_edit_taxes:
                description: Toggle Flag - Allow a role to edit taxes.
                default: op




      lands.admin.*:
        description: Access to all admin actions. Commands require execution of /Lands edit <land> (to select the land).
        default: op
        children:
          lands.admin.land_edit:
            description: Allow to edit other lands /Lands edit
            default: op
          lands.admin.land_delete:
            description: Allow to delete other lands or unclaim chunks from other lands.
            default: op
          lands.admin.land_setowner:
            description: Allow the usage of /Lands setowner for lands the player doesn't own
            default: op
          lands.admin.setting_edit_land:
            description: Edit land settings of other lands (like mob spawning etc.)
            default: op
          lands.admin.setting_edit_role:
            description: Edit role settings of other lands.
            default: op
          lands.admin.setting_edit_taxes:
            description: Edit taxes settings of other lands.
            default: op

          lands.admin.command.*:
            description: Access to all admin commands
            default: op
            children:
              lands.admin.command.reload:
                description: Access to /Lands reload
                default: op
              lands.admin.command.wilderness:
                description: Open wilderness menu /Lands admin wilderness
                default: op
              lands.admin.command.land.*:
                description: Access to admin land commands
                default: op
                children:
                  lands.admin.command.land.delete:
                    description: Delete land
                    default: op
                  lands.admin.command.land.edit:
                    description: Open GUI for land
                    default: op
                  lands.admin.command.land.trust:
                    description: Trust players to land
                    default: op
                  lands.admin.command.land.untrust:
                    description: Untrust players from land
                    default: op
                  lands.admin.command.land.rename:
                    description: Rename land
                    default: op
                  lands.admin.command.land.settings.reset:
                    description: Reset settings of land
                    default: op
                  lands.admin.command.land.setowner:
                    description: Set new owner for land
                    default: op
              lands.admin.command.give.claimblock:
                description: Give claimblocks to player
                default: op
              lands.admin.command.import:
                description: Import data from other plugins
                default: op
              lands.admin.command.safezone:
                description: Edit safezones
                default: op

  wars.*:
    description: Access to all wars actions.
    default: op
    children:
      wars.command.*:
        description: Access to all /wars commands.
        default: op
        children:
          wars.command.declare:
            description: Access to /Wars declare
            default: op
          wars.command.info:
            description: Access to /Wars info
            default: op
          wars.command.menu:
            description: Access to /Wars menu
            default: op

